### ISSUE TITLE
Add order id to print receipt and remove double pages

### ISSUE THREAD

**Issue by tbaustin** [escaladesports/zygote-cart#234]

**Comment by MastaAaron** [comment]
The issue with duplicate receipts printing is caused by the cart being `position: fixed` while the underlying page content prints multiple pages. A fix can be applied on a site using Zygote by using the following CSS:

```css
@media print {
	body.zygoteOpen *:not(.zygote):not(.zygoteCart):not(.zygoteStep) {
		position: static !important;
		max-height: 100vh !important;
		overflow: hidden !important;
	}
}
```
